# Generated by Django 5.0.1 on 2024-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='memory',
        ),
        migrations.AlterField(
            model_name='product',
            name='color_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название цвета'),
        ),
    ]
