# Generated by Django 5.0.1 on 2024-01-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0002_remove_product_memory_alter_product_color_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ширина'),
        ),
    ]
