# Generated by Django 5.0.1 on 2024-01-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0003_remove_product_created_at_remove_product_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Краткое описание'),
        ),
    ]
