# Generated by Django 5.0.1 on 2024-01-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0004_product_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
