# Generated by Django 5.0.1 on 2024-01-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0005_remove_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('email', models.CharField(max_length=300, verbose_name='почта')),
                ('text', models.CharField(max_length=300, verbose_name='Саобщение')),
            ],
            options={
                'verbose_name': 'Саобщение',
                'verbose_name_plural': 'Саобшении',
            },
        ),
    ]
