# Generated by Django 5.0.1 on 2024-02-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0008_favoriteproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл'),
        ),
    ]
