# Generated by Django 5.0.2 on 2024-02-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0012_remove_product_color_code_remove_product_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loft.product', verbose_name='colors'),
        ),
    ]
