# Generated by Django 5.0.1 on 2024-02-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0013_alter_colors_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='loft.product', verbose_name='colors'),
        ),
    ]
