# Generated by Django 5.0.1 on 2024-02-17 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0014_alter_colors_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/', verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ширина')),
                ('depth', models.CharField(blank=True, max_length=400, null=True, verbose_name='Глибина')),
                ('height', models.CharField(blank=True, max_length=400, null=True, verbose_name='Высота')),
                ('long', models.CharField(blank=True, max_length=400, null=True, verbose_name='Длина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='loft.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Размер Товара',
                'verbose_name_plural': 'Размеры Товаров',
            },
        ),
    ]
