# Generated by Django 5.0.1 on 2024-02-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0016_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
