# Generated by Django 5.0.1 on 2024-02-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0018_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
