# Generated by Django 5.0.1 on 2024-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0023_product_color_code_product_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Глибина'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='long',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ширина'),
        ),
    ]
