# Generated by Django 5.0.1 on 2024-02-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0024_product_depth_product_height_product_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='depth',
            new_name='size_depth',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='height',
            new_name='size_height',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='long',
            new_name='size_long',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='width',
            new_name='size_width',
        ),
    ]
