# Generated by Django 5.0.1 on 2024-03-02 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0027_paidgoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Состояние заказа')),
                ('shipping', models.BooleanField(default=True, verbose_name='Доставка')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Сумма товаров')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loft.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loft.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Оплаченный товар',
                'verbose_name_plural': 'Оплаченные товары',
            },
        ),
        migrations.CreateModel(
            name='PaidProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена продукта')),
                ('paid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loft.paid', verbose_name='Заказ №')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loft.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Оплаченный товар',
                'verbose_name_plural': 'Оплаченные товары',
            },
        ),
        migrations.DeleteModel(
            name='PaidGoods',
        ),
    ]
