# Generated by Django 5.0.1 on 2024-03-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0028_paid_paidproduct_delete_paidgoods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paid',
            options={'verbose_name': 'Оплаченный заказ', 'verbose_name_plural': 'Оплаченные заказы'},
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
