# Generated by Django 5.0.1 on 2024-03-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0030_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidproduct',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loft.customer', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='paidproduct',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Состояние заказа'),
        ),
    ]
