# Generated by Django 5.0.1 on 2024-03-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0032_remove_paidproduct_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paid',
            name='price',
        ),
    ]
