# Generated by Django 5.0.1 on 2024-03-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0033_remove_paid_order_remove_paid_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='added_at',
            new_name='created_at',
        ),
    ]
