# Generated by Django 5.0.1 on 2024-03-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0034_rename_added_at_orderproduct_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='created_at',
            new_name='added_at',
        ),
    ]
